name: Daily Commit

on:
  schedule:
    - cron: '41 19 * * *' # Runs every day at midnight UTC

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make a change
      - name: Make Changes
        run: |
          echo "Commit made on $(date)" >> daily_commit_log.txt

      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Step 4: Commit and push changes
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Daily commit - $(date)"
          git push
