name: Daily Commit

on:
  schedule:
    - cron: '48 19 * * *' # Scheduled time (adjust as needed)
  workflow_dispatch:       # Allows manual runs

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Changes
        run: echo "Commit made on $(date)" >> daily_commit_log.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Daily commit - $(date)"
          git push
